version: '3.4'
services:
  db:
    image: stonefury/postgres
    restart: always
    environment:
      - POSTGRES_USER=oreilly
      - POSTGRES_PASSWORD=hunter2
    ports:
      - '5432:5432'

  web:
    image: eddenburrow/apidemo
    restart: always
    ports:
      - '8080:8080'
